### ISSUE TITLE
Linting support 

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy-language-server#180]
Just starting this for finding out what is needed for linting support... (there was a recent discussion which I can't find anymore). I recall:

- Structured output: like json
- line numbers.

Guess line numbers would be difficult, since we have only the lxml representation of the tool XML while linting. So how about the XPath?

**Comment by bernt-matthias** [comment]
Question is also if one would rely on the output of `planemo lint` or call the functions in the `tool-util` package directly.

**Comment by davelopez** [comment]
So the initial idea about linting in the GLS extension was to reuse as much as possible what `planemo lint` already does. Many other extensions ([like the Python extension](https://github.com/microsoft/vscode-python/tree/main/src/client/linters)) rely on other CLI tools for linting. They usually just run the tool in the background and parse the standard output to get the following basic information for each issue found by the linter:
```js
{
    "line": int,
    "column": int,
    "message": string,
    "severity": string,
}
```
Since planemo was already integrated to run the tests and display the results directly on VSCode with https://github.com/galaxyproject/galaxy-language-server/pull/110 we just thought of doing the same for linting whenever your tool XML source is saved. But instead of just parsing the standard output of planemo, maybe trying to get the information from a structured output file (ideally JSON but XUnit also was considered, see https://github.com/galaxyproject/planemo/issues/1139) since it will be easier and less error-prone. 

> Question is also if one would rely on the output of planemo lint or call the functions in the tool-util package directly.

Back then, I had no idea that all this linting functionality was actually part of the `galaxy-tool-utils` package which we already depend on so I guess directly using this will be much more convenient and faster than actually running `planemo lint` and then either parsing output or read a file from disk to get the linting information. So I think this is definitely the direction to go.

> Guess line numbers would be difficult, since we have only the lxml representation of the tool XML while linting. So how about the XPath?

Yeah, that was one of the main reasons this feature was *pushed into the future* :laughing: I started using `lxml` too at the beginning of the project but was frustrated because it was very limited for getting this file positions and also it just didn't work with XML files "under construction", so in the end, I had to use a custom parser that doesn't choke on incomplete or broken XML and also provides accurate document position for each *token*.
Another concern about line positions is that (I'm not really sure right now) the linting is done after macro expansion, so these positions (if we could actually get them) are relative to the expanded version of the document and not the tool XML original source which is the one in which we need to display the squiggles for the linting errors. I guess if we can get the `XPath` for each linting error or warning will be of help, basically, anything that helps to point out where the issue is in the document and finally translate it to a [line, position].

@bernt-matthias thanks so much for lighting up the discussion. I think integrated support for linting will be a huge addition to the extension so any help or ideas on that would be awesome to have.

**Comment by bernt-matthias** [comment]
Just found out that `element.sourceline` is a thing, but you are right this probably won't work with macros. 

But also locating an xpath in a tool with macros might be tricky. 

I researched a bit what actually happens in `planemo lint`: https://github.com/galaxyproject/planemo/blob/b96b1bb07726ec64eea7433d0571bdf771639507/planemo/tool_lint.py#L46

calls 

https://github.com/galaxyproject/galaxy/blob/38a69b19b55b41e2fc079de94a94eee5c1c6a9f5/lib/galaxy/tool_util/lint.py#L14

which then calls all linters in https://github.com/galaxyproject/galaxy/tree/dev/lib/galaxy/tool_util/linters

The function (`lint_tool_source`) works with a `LintContext` object which contains the outputs of the linters (currently only the messages sorted in warn, error, ...). Should be easy to extend this to contain more info like line numbers or xpath (or maybe just a reference to the lxml object causing the linter error ..).

**Comment by bernt-matthias** [comment]
>  also it just didn't work with XML files "under construction"

Maybe the recover mode might be of help: https://lxml.de/parsing.html#parser-options

**Comment by davelopez** [comment]
> The function (lint_tool_source) works with a LintContext object which contains the outputs of the linters (currently only the messages sorted in warn, error, ...) .. but it does not return this object (ie planemo only gets the final status). Should be easy to extend this to make the LintContext contain more info like line numbers or xpath (or maybe just a reference to the lxml object causing the linter error ..). And maybe also return the LintContext

That is starting to sound like a plan :)

> Maybe the recover mode might be of help: https://lxml.de/parsing.html#parser-options

I vaguely recall trying that option back then, but it was actually modifying the source XML *to try and fix it* (or was it beautifulsoup? :thinking: ) so it was even worse :disappointed:. But I think this is ok, we probably don't want to lint other stuff unless the XML is completely well-formed, so the linter on saving will fire only for well-formed documents, that way the *Problems tab* will first show the syntax errors which are of high priority and then other galaxy tools specific linting issues.

**Comment by bernt-matthias** [comment]
Here is something to play with https://github.com/galaxyproject/galaxy/pull/12978

**Comment by davelopez** [comment]
Waiting for the new version of `galaxy-tool-util` to be released
